package io.datawire.loom.exception


class ExistsAlreadyException(val existsAlready: ExistsAlready): RuntimeException()